### ISSUE TITLE
The our team page should be fixed.

### ISSUE THREAD

**Issue by t2013anurag** [GDGVIT/gdgvit2016.github.io#1]
![11](https://cloud.githubusercontent.com/assets/9719394/16425439/5857aed6-3d82-11e6-9c8b-7d99b10fe51e.png)

@ashwini0529

**Comment by ashwini0529** [comment]
Just uploaded the previous site. I've already told Rishi to fix this. Will be fine shortly.

**Comment by t2013anurag** [comment]
@ashwini0529 acknowledged. Ping me when solved.

**Comment by ashwini0529** [comment]
@t2013anurag , sure!

**Comment by ashwini0529** [comment]
Hey, @t2013anurag , The issue is fixed in the commit  :  [`de31c41`](https://github.com/GDGVIT/gdgvit.github.io/commit/de31c417112acd49a18553c14328be4aa5955c9b) .
Please check once.
