### ISSUE TITLE
How to create and Fix an issue 

### ISSUE THREAD

**Issue by t2013anurag** [GDGVIT/gdgvit2016.github.io#2]
Things to keep in mind 

@GDGVIT/owners  @GDGVIT/team-gdg-vit-vellore 

1). Include a single descriptive commit per feature bug.
2).  All commit messages should mention the issue number at the end.. like 'fixes #xxxx' so it links on github.  Ex. Fixed css for #1

**Comment by ashwini0529** [comment]
@t2013anurag  I guess this doesn't comes under issue. You can create Wiki, or README for that.

**Comment by ashwini0529** [comment]
@t2013anurag , I guess you yourself mentioned that such things doesn't comes under issue [here](https://github.com/GDGVIT/BroSourceAndroid/issues/1#issuecomment-227872923)
I hope you'll keep that in mind before creating an issue.
To create a README or a GUIDELINES file, just end it up with `.md` extension.
For example, `GUIDELINES.md`
